### ISSUE TITLE
Add Ability to Include External Videos in Series 📃

### ISSUE THREAD

**Issue by duskvirkus** [CodingTrain/website#2810]
On YouTube a video can be part of multiple playlists but on The Coding Train site videos can only be under one series. An example is the programming with text series where there are many coding challenges integrated into the playlist on youtube but none on that page on the site. 

https://www.youtube.com/playlist?list=PLRqwX-V7Uu6YrbSJBg32eTzUU50E2B8Ch
https://thecodingtrain.com/learning/programming-with-text/

Would like to be able to add links to other videos in the index.md page of a series. Like so:
```yaml
---
title: Programming With Text
layout: series-index
external_videos:
  - title: "Diastic Machine"
    series_number: 1.55
    show_number: false
    url: /CodingChallenges/037-diastic
  - title: "Word Interactor"
    series_number: 2.95
    show_number: false
    url: /CodingChallenges/038-word-interactor
... And so on.
```

This would mean changing the series index jekyll page. Also adding functionality to hide numbers on particular videos on the series page. Adding a format to the unit testing.

Another thing that I'm not sure if it would be best as part of this issue or another issue is this would probably break the back and forward arrows on the video pages so it would be great to fix that if it ends up being a problem.

Planning to work on this at some point in the next few weeks but if someone is feeling ambitious and wants to take this on feel free to let me know. It would be a rather involved project and I wouldn't suggest taking it on unless you know jekyll rather well or are willing to spend some time learning it.
