### ISSUE TITLE
Fix YouTube Description Script - Releative Links 😞

### ISSUE THREAD

**Issue by violetcraze** [CodingTrain/website#2863]
Making note that YouTube description script fails when a link in the links category is a relative link.

Example:
```
links:
  - title: "Discord (Website)"
    url: https://discord.com/
  - title: "Discord Developer Portal"
    url: https://discord.com/developers/docs/intro
  - title: "The Coding Train Discord"
    url: /discord
```

Creates:

Links discussed in this video:
🔗 Discord (Website): https://discord.com/
🔗 Discord Developer Portal: https://discord.com/developers/docs/intro
🔗 The Coding Train Discord: /discord

Expected Output is:

Links discussed in this video:
🔗 Discord (Website): https://discord.com/
🔗 Discord Developer Portal: https://discord.com/developers/docs/intro
🔗 The Coding Train Discord: https://thecodingtrain.com/discord
